"""Committed figures. Every one of them is regenerated by `python -m ravon_ml.cli`.

Charts here exist to make a claim checkable at a glance, not to decorate the README.
Each function returns the path it wrote so the CLI can record it in `metrics.json`.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # no display in CI

import matplotlib.pyplot as plt
import numpy as np

from .metrics import UNIFORM_VARIANCE, coverage_curve, pit_values

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"

RAVON_RED = "#FF3008"
RAVON_DARK = "#1A1A2E"
GREY = "#9AA0A6"


def _style(ax) -> None:
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="y", alpha=0.25, linewidth=0.6)
    ax.set_axisbelow(True)


def pit_histogram(models_and_params, y, path: Path | None = None) -> Path:
    """PIT histograms side by side, with the uniform reference.

    Flat is calibrated. A U means under-dispersion (predictions too narrow, reality in
    the tails more often than promised). A central hump means over-dispersion.
    """
    path = path or REPORTS_DIR / "pit_histogram.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    n = len(models_and_params)
    fig, axes = plt.subplots(1, n, figsize=(4.6 * n, 3.8), sharey=True)
    axes = np.atleast_1d(axes)

    for ax, (label, params) in zip(axes, models_and_params):
        u = pit_values(params, y)
        ax.hist(u, bins=20, range=(0, 1), color=RAVON_RED, alpha=0.85,
                edgecolor="white", linewidth=0.6)
        ax.axhline(len(u) / 20, color=RAVON_DARK, linestyle="--", linewidth=1.4,
                   label="uniform (calibrated)")
        variance = float(np.var(u, ddof=1))
        ax.set_title(
            f"{label}\nPIT var {variance:.4f} vs {UNIFORM_VARIANCE:.4f} ideal",
            fontsize=10,
        )
        ax.set_xlabel("PIT value  $F_i(y_i)$")
        _style(ax)
    axes[0].set_ylabel("count")
    axes[0].legend(fontsize=8, frameon=False)
    fig.suptitle(
        "Probability integral transform — flat means calibrated", fontsize=12,
        color=RAVON_DARK,
    )
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def calibration_plot(models_and_params, y, path: Path | None = None) -> Path:
    """Nominal quantile level against realised coverage. The diagonal is perfect."""
    path = path or REPORTS_DIR / "calibration.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(11, 4.4))

    colours = [RAVON_RED, RAVON_DARK, "#2E86C1", "#27AE60"]
    ax.plot([0, 1], [0, 1], color=GREY, linestyle="--", linewidth=1.3,
            label="perfectly calibrated")
    for colour, (label, params) in zip(colours, models_and_params):
        levels, realised = coverage_curve(params, y)
        ax.plot(levels, realised, color=colour, linewidth=2, label=label)
        ax2.plot(levels, realised - levels, color=colour, linewidth=2, label=label)
    ax.set_xlabel("nominal quantile level")
    ax.set_ylabel("realised coverage")
    ax.set_title("Calibration", fontsize=11)
    ax.legend(fontsize=8, frameon=False)
    _style(ax)

    ax2.axhline(0, color=GREY, linestyle="--", linewidth=1.3)
    ax2.set_xlabel("nominal quantile level")
    ax2.set_ylabel("realised − nominal")
    ax2.set_title("Calibration error (negative = late more often than promised)",
                  fontsize=11)
    _style(ax2)

    fig.suptitle("ETA calibration on held-out simulator days", fontsize=12,
                 color=RAVON_DARK)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def recovery_plot(recovery_rows, transform_example, path: Path | None = None) -> Path:
    """Parameter recovery, plus the log-log survival line the fit is built on."""
    path = path or REPORTS_DIR / "weibull_recovery.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(11, 4.4))

    true_k = [r["true_shape"] for r in recovery_rows]
    fitted_k = [r["fitted_shape"] for r in recovery_rows]
    lo, hi = min(true_k + fitted_k) * 0.9, max(true_k + fitted_k) * 1.1
    ax.plot([lo, hi], [lo, hi], color=GREY, linestyle="--", linewidth=1.3,
            label="exact recovery")
    ax.scatter(true_k, fitted_k, color=RAVON_RED, s=45, zorder=3, label="interval regression")
    ax.scatter(true_k, [r["mle_shape"] for r in recovery_rows], color=RAVON_DARK, s=30,
               marker="x", zorder=3, label="maximum likelihood")
    ax.set_xlabel("true shape $k$")
    ax.set_ylabel("recovered shape $k$")
    ax.set_title("Parameter recovery from known Weibulls", fontsize=11)
    ax.legend(fontsize=8, frameon=False)
    _style(ax)

    x, y, fitted = transform_example
    ax2.scatter(x, y, color=RAVON_RED, s=28, zorder=3, label="6-minute buckets")
    ax2.plot(x, fitted, color=RAVON_DARK, linewidth=2, label="OLS fit")
    ax2.set_xlabel(r"$\log(t - \gamma)$")
    ax2.set_ylabel(r"$\log(-\log S(t))$")
    ax2.set_title("The transform that makes the fit linear", fontsize=11)
    ax2.legend(fontsize=8, frameon=False)
    _style(ax2)

    fig.suptitle("Interval regression validated against known ground truth",
                 fontsize=12, color=RAVON_DARK)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def quantile_cost_plot(sweeps, path: Path | None = None) -> Path:
    """Realised asymmetric cost against quote quantile, with the derived optimum."""
    path = path or REPORTS_DIR / "quantile_cost.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.4, 4.6))

    colours = plt.cm.autumn(np.linspace(0.05, 0.75, len(sweeps)))
    for colour, sweep in zip(colours, sweeps):
        levels, costs = sweep["levels"], sweep["costs"]
        ax.plot(levels, costs, color=colour, linewidth=2,
                label=f"{sweep['ratio']:.0f}:1  →  derived q*={sweep['derived']:.2f}")
        ax.axvline(sweep["derived"], color=colour, linestyle=":", linewidth=1.4)
        ax.scatter([levels[int(np.argmin(costs))]], [float(np.min(costs))],
                   color=colour, s=45, zorder=4, edgecolor="white", linewidth=0.8)
    ax.set_xlabel("quote quantile level")
    ax.set_ylabel("realised mean cost (cost units)")
    ax.set_title(
        "Decision layer: the derived newsvendor quantile lands on the empirical minimum\n"
        "dotted line = $c_{late}/(c_{late}+c_{early})$,  dot = measured argmin",
        fontsize=10, color=RAVON_DARK,
    )
    ax.legend(fontsize=8, frameon=False, title="late:early cost ratio",
              title_fontsize=8)
    _style(ax)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def anomaly_plot(sweeps, gap_history, mde_rows, path: Path | None = None) -> Path:
    """Detection rate vs magnitude, the gap window's effect, and the volume wall."""
    path = path or REPORTS_DIR / "anomaly_detection.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 3, figsize=(15.5, 4.4))

    ax = axes[0]
    colours = [RAVON_RED, RAVON_DARK, "#2E86C1"]
    for colour, sweep in zip(colours, sweeps):
        ax.plot(sweep["magnitudes"], sweep["detection_rate"], color=colour,
                marker="o", linewidth=2, label=f"test window = {sweep['test_days']} day(s)")
    ax.set_xlabel("injected kitchen slowdown (minutes)")
    ax.set_ylabel("detection rate")
    ax.set_ylim(-0.05, 1.05)
    ax.set_title("Detection rate vs incident size", fontsize=11)
    ax.legend(fontsize=8, frameon=False)
    _style(ax)

    ax = axes[1]
    for colour, (label, frame) in zip([RAVON_RED, RAVON_DARK], gap_history.items()):
        ax.plot(frame["days_elapsed"], frame["truth_z"], color=colour, marker="o",
                markersize=3.5, linewidth=2, label=label)
    ax.axhline(3.0, color=GREY, linestyle="--", linewidth=1.3, label="σ = 3 gate")
    ax.set_xlabel("days since the trend started")
    ax.set_ylabel("Z-score of the affected segment")
    ax.set_title("Why the 7-day gap exists:\na ramp that pollutes its own baseline",
                 fontsize=10)
    ax.legend(fontsize=8, frameon=False)
    _style(ax)

    ax = axes[2]
    for colour, row in zip(colours, mde_rows):
        ax.plot(row["test_days"], row["mde"], color=colour, marker="o", linewidth=2,
                label=f"{row['label']} ({row['orders_per_day']:.0f} orders/day)")
    ax.set_xlabel("test window (days)")
    ax.set_ylabel("minimum detectable slowdown (minutes)")
    ax.set_title("The volume wall: sensitivity is set by\nsegment volume, not by σ",
                 fontsize=10)
    ax.legend(fontsize=8, frameon=False)
    _style(ax)

    fig.suptitle("Anomaly detection, validated against injected ground truth",
                 fontsize=12, color=RAVON_DARK)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path
